# Generated by Django 3.2.12 on 2022-04-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='abonement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.abon', verbose_name='Abonement'),
        ),
    ]
